# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ALESCOPE
email: marion.weinzierl@durham.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Academy of Large and Extreme Scale Computing, Optimisation and Performance Engineering
twitter_username: hpcsoftware_
github_username: marionbweinzierl
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
#remote_theme: mmistakes/minimal-mistakes
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: GB
#highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "ALESCOPE"
  avatar : #"/assets/images/bio-photo.jpg"
  bio    : "Academy of Large and Extreme Scale Computing, Optimisation and Performance Engineering "
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://alescope.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hpcsoftware_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ALESCOPE"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hpcsoftware_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ALESCOPE"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: #false
      read_time: true
      comments: #true
      share: #true
      related: #true
      sidebar:
        nav: "Posts"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: #false
      sidebar:
        nav: "alescope"

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
